version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: next
    versions:
    - 10.1.1
    - 10.1.3
  - dependency-name: styled-components
    versions:
    - 5.2.2
